name: Deploy VK Cloud
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install & Build
      run: |
        npm install --legacy-peer-deps
        npm run build
        
    - name: Show files
      run: ls -la
        
    - name: Deploy to VK Cloud
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.VK_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.VK_SECRET_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region ru-msk
        aws s3 sync ./out/ s3://${{ secrets.VK_BUCKET }}/ \
          --endpoint-url https://hb.ru-msk.vkcloud-storage.ru \
          --delete
